"""add cascade delete for cases and its documents

Revision ID: 292c57aec121
Revises: 32086489177f
Create Date: 2026-07-03 23:55:48.997655

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '292c57aec121'
down_revision: Union[str, Sequence[str], None] = '32086489177f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_documents', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('case_documents_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('cases_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('cases_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('case_documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('case_documents_user_id_fkey'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
