"""add user id for dcuments

Revision ID: 820e01178f0e
Revises: 9274988bd9a2
Create Date: 2026-05-26 16:12:05.921858

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '820e01178f0e'
down_revision: Union[str, Sequence[str], None] = '9274988bd9a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regulations_documents', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'regulations_documents', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'regulations_documents', type_='foreignkey')
    op.drop_column('regulations_documents', 'user_id')
    # ### end Alembic commands ###
