FROM python:3.13-slim-trixie

RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender1 \
    libxcb1 \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir uv

RUN useradd -m text_transformator
WORKDIR /text_transformator
RUN chown -R text_transformator /text_transformator
USER text_transformator

COPY pyproject.toml pyproject.toml
COPY --chown=text_transformator:text_transformator uv.lock uv.lock

RUN uv --no-cache sync

COPY model_download.py model_download.py

RUN .venv/bin/python model_download.py

COPY src src

EXPOSE 8080

ENV PATH="/text_transformator/.venv/bin:$PATH"

ENTRYPOINT ["granian", "--port", "8080", "--host", "0.0.0.0", "--interface", "asgi", "src.main:app"]