[project]
name = "prawobiorca-backend"
version = "0.47.5"
description = "Law acts search engine with AI features."
readme = "README.md"
requires-python = "==3.14.*"
dependencies = [
    "asyncpg==0.31.*",
    "bcrypt==5.0.*",
    "email-validator==2.3.*",
    "fastapi==0.136.*",
    "granian==2.7.*",
    "httpx2==2.3.*",
    "pgvector==0.4.*",
    "pydantic==2.13.*",
    "pydantic-settings==2.14.*",
    "python-multipart==0.0.32",
    "sqlalchemy[asyncio]==2.0.*",
]

[dependency-groups]
dev = [
    "granian[reload]==2.7.*",
    "ruff==0.15.*",
]
docs = [
    "mkdocstrings[python]==1.0.*",
    "zensical==0.0.45",
]
google-cloud = [
    "google-cloud-storage==3.11.*",
]
local-storage = [
    "aiofiles==25.1.*",
]

test = [
    "alembic==1.18.*",
    "pytest==9.1.*",
    "pytest-asyncio==1.4.*",
    "pytest-cov==7.1.*",
    "testcontainers[postgres]==4.14.*",
]

[tool.pytest.ini_options]
pythonpath = ["."]
asyncio_default_fixture_loop_scope = "function"
asyncio_mode = "auto"

[tool.ruff]
line-length = 120
target-version = "py314"

exclude = [
    "alembic",
]

[tool.ruff.lint]
select = ["S", "I", "E", "F", "B"]
ignore = ["B904", "B008"]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["S"]
"scripts/*" = ["S"]
"cicd/*" = ["S"]
