[project]
name = "prawobiorca"
version = "0.1.0"
description = "Law acts search engine with AI features."
readme = "README.md"
requires-python = "==3.14.*"
dependencies = [
    "poethepoet==0.48.*",
    "ruff==0.16.*",
    "mkdocstrings[python]==1.0.*",
    "zensical==0.0.59",
]

[tool.poe]
include = "poe.toml"
executor.type = "simple"

[tool.ruff]
extend = "ruff.toml"
