"""Change column name in case_articles

Revision ID: 8a689632de01
Revises: 8d1124640ec9
Create Date: 2026-03-08 09:03:31.715587

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8a689632de01'
down_revision: Union[str, Sequence[str], None] = '8d1124640ec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_articles', sa.Column('content', sa.Text(), nullable=False))
    op.drop_column('case_articles', 'article_content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_articles', sa.Column('article_content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('case_articles', 'content')
    # ### end Alembic commands ###
