"""add cascade delete for tokens

Revision ID: a9f8d0aa9530
Revises: 97e6e7761096
Create Date: 2026-07-23 23:41:24.222086

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a9f8d0aa9530'
down_revision: Union[str, Sequence[str], None] = '97e6e7761096'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_tokens_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('users_tokens_user_id_fkey'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
