[tasks]
dev = "uv run scripts/local/dev.py"
run_locally = "uv run scripts/local/run.py"
run_locally_down = "uv run scripts/local/stop.py"
test = "uv run --group test pytest -c tools/config/pytest.ini tests/unit"
test_integration = "uv run --group test pytest -c tools/config/pytest.ini tests/integration"
test_slow = "uv run --group test pytest -c tools/config/pytest.ini -m slow tests/integration"
build_app = "podman image build --tag=prawobiorca-backend ."
build_embedding-service = "podman image build --tag=embedding-service embedding-service"
build_extraction-service = "podman image build --tag=extraction-service extraction-service"
upgrade_db = "uv run --group test alembic -c tools/config/alembic.ini upgrade head"
seed = "uv run scripts/init/seed_relational_db.py"
init_regulations = "uv run scripts/init/init_regulations.py"

[tasks.cov]
sequence = [
    { cmd = "uv run coverage erase" },
    { cmd = "uv run pytest tests/unit --cov=app" },
    { cmd = "uv run coverage report -m --skip-covered --fail-under=95 --sort=Cover" }
]

[tasks.build_images]
sequence = ["build_app", "build_embedding-service", "build_extraction-service"]

[tasks.init_db]
sequence = ["upgrade_db", "seed", "init_regulations"]
