[pytest]
pythonpath = ../..
asyncio_default_fixture_loop_scope = function
asyncio_mode = auto
addopts = -m "not slow"
markers =
    slow: marks tests as slow

filterwarnings =
    ignore::DeprecationWarning:starlette.testclient