FROM python:3.14-slim-trixie

RUN pip install --no-cache uv==0.12.*

RUN useradd -r prawobiorca_app

WORKDIR /prawobiorca
RUN chown prawobiorca_app /prawobiorca


USER prawobiorca_app

COPY pyproject.toml pyproject.toml
RUN uv sync --compile-bytecode --no-cache --no-default-groups

ENV PATH="/prawobiorca/.venv/bin:$PATH"

COPY src src
COPY alembic.ini alembic.ini
COPY alembic alembic

EXPOSE 8000

CMD ["granian", "--port", "8000", "--host", "0.0.0.0", "--interface", "asgi", "src.main:prawobiorca"]
