[pytest]
pythonpath = .
asyncio_default_fixture_loop_scope = session
asyncio_default_test_loop_scope = session
asyncio_mode = auto
addopts = -m "not slow"
markers =
    slow: marks tests as slow

filterwarnings =
    ignore::DeprecationWarning:starlette.testclient