from typing import Protocol

from app.application.dtos.files import FileData


class PublicFilesRepository(Protocol):
    async def get_file(self, file_name: str) -> bytes: ...

    async def list_files(self) -> list[str]: ...


class UsersFilesRepository(Protocol):
    def __init__(self, user_id: str): ...

    async def upload_file(self, file_data: FileData): ...

    async def delete_file(self, file_name: str) -> None: ...

    async def get_file(self, file_name: str) -> bytes: ...

    async def list_files(self) -> list[str]: ...
