from typing import Protocol
from uuid import UUID

from app.application.dtos.regulations import RegulationData, RegulationRepresentation
from app.application.interfaces.relational import AsyncSession
from app.domain.value_objects.regulations import RegulationType, RegulationRegistrationData


class RegulationsRepository(Protocol):
    def __init__(self): ...

    async def get_regulation(self, id_: UUID) -> bytes: ...

    async def upload_regulation(self, id_: UUID, file: bytes) -> None: ...

    async def delete_regulation(self, id_: UUID) -> None: ...


class RegulationsManager(Protocol):
    def __init__(self, session: AsyncSession, user_id: UUID | None): ...

    async def list_regulations(self, document_type: RegulationType | None) -> list[RegulationRepresentation]: ...

    async def register_regulation(self, regulation_registration_data: RegulationRegistrationData) -> UUID: ...

    async def unregister_regulation(self, regulation_id: UUID) -> None: ...

    async def mark_as_prepared(self, regulation_id: UUID) -> None: ...

    async def get_regulation_representation(self, regulation_id: UUID) -> RegulationRepresentation: ...
