from pathlib import Path

from pydantic_settings import BaseSettings, SettingsConfigDict


class ObjectStorageSettings(BaseSettings):
    ENDPOINT_URL: str = ...
    REGION: str = ...
    ACCESS_KEY: str = ...
    SECRET_KEY: str = ...
    BUCKET: str = ...
    SIGNED_URL_EXPIRATION_SECONDS: int = ...
    MAX_FILE_SIZE_BYTES: int = ...

    model_config = SettingsConfigDict(
        env_file=Path(".env"), extra="ignore", case_sensitive=True, frozen=True, env_prefix="OBJECT_STORAGE_"
    )


object_storage_settings = ObjectStorageSettings()
