from pathlib import Path

from pydantic_settings import BaseSettings, SettingsConfigDict


class RelationalDatabaseSettings(BaseSettings):
    RELATIONAL_DB_DRIVER: str = ...
    RELATIONAL_DB_DB_USER: str = ...
    RELATIONAL_DB_PASSWORD: str = ...
    RELATIONAL_DB_HOST: str = ...
    RELATIONAL_DB_PORT: int = ...
    RELATIONAL_DB_DB_NAME: str = ...
    RELATIONAL_DB_POOL_SIZE: int = ...
    RELATIONAL_DB_MAX_OVERFLOW: int = ...
    RELATIONAL_DB_POOL_TIMEOUT: int = ...
    RELATIONAL_DB_POOL_RECYCLE: int = ...

    model_config = SettingsConfigDict(
        env_file=Path(".env"), extra="ignore", case_sensitive=True, frozen=True, env_prefix="RELATIONAL_DB_"
    )


relational_db_settings = RelationalDatabaseSettings()
