from pathlib import Path

from pydantic_settings import BaseSettings, SettingsConfigDict


class RelationalDatabaseSettings(BaseSettings):
    DRIVER: str = ...
    DB_USER: str = ...
    PASSWORD: str = ...
    HOST: str = ...
    PORT: int = ...
    DB_NAME: str = ...
    POOL_SIZE: int = ...
    MAX_OVERFLOW: int = ...
    POOL_TIMEOUT: int = ...
    POOL_RECYCLE: int = ...

    model_config = SettingsConfigDict(
        env_file=Path(".env"), extra="ignore", case_sensitive=True, frozen=True, env_prefix="RELATIONAL_DB_"
    )


relational_db_settings = RelationalDatabaseSettings()
