"""add cascade delete for regulations

Revision ID: 50f8b07c8a77
Revises: 9ea79db87ac3
Create Date: 2026-07-04 23:27:05.521878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50f8b07c8a77'
down_revision: Union[str, Sequence[str], None] = '9ea79db87ac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regulations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('regulations_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regulations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('regulations_user_id_fkey'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
