"""Change files table collumns names

Revision ID: 8d1124640ec9
Revises: 98425aa7315d
Create Date: 2026-03-08 00:56:42.026783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d1124640ec9'
down_revision: Union[str, Sequence[str], None] = '98425aa7315d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('public_files', sa.Column('hash', sa.String(length=32), nullable=False))
    op.drop_column('public_files', 'file_hash')
    op.add_column('users_files', sa.Column('hash', sa.LargeBinary(length=32), nullable=False))
    op.drop_column('users_files', 'file_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_files', sa.Column('file_hash', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.drop_column('users_files', 'hash')
    op.add_column('public_files', sa.Column('file_hash', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_column('public_files', 'hash')
    # ### end Alembic commands ###
