"""remove qdrant and merge files tables

Revision ID: 9274988bd9a2
Revises: bf8a3b670e22
Create Date: 2026-05-26 07:42:32.520097

"""
import pgvector
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '9274988bd9a2'
down_revision: Union[str, Sequence[str], None] = 'bf8a3b670e22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regulations',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('presentation_name', sa.String(length=255), nullable=False),
    sa.Column('is_prepared', sa.Boolean(), nullable=False),
    sa.Column('regulation_type', sa.Enum('ACT', 'DECREE', 'STATUTE', name='regulationtype'), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('create_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regulations_documents',
    sa.Column('header', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('vector', Vector(dim=768), nullable=False),
    sa.Column('regulation_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('create_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['regulation_id'], ['regulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('users_files')
    op.drop_table('public_files')
    op.add_column('case_articles', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.drop_index(op.f('ix_case_articles_case_id'), table_name='case_articles')
    op.create_foreign_key(None, 'case_articles', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_cases_user_id'), table_name='cases')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_index(op.f('ix_cases_user_id'), 'cases', ['user_id'], unique=False)
    op.drop_constraint(None, 'case_articles', type_='foreignkey')
    op.create_index(op.f('ix_case_articles_case_id'), 'case_articles', ['case_id'], unique=False)
    op.drop_column('case_articles', 'user_id')
    op.create_table('public_files',
    sa.Column('presentation_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_prepared', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('create_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('hash', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('document_type', postgresql.ENUM('ACT', 'DECREE', 'STATUTE', name='documenttype'), autoincrement=False, nullable=True)
    )
    op.create_table('users_files',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('presentation_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_prepared', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('create_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('hash', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('document_type', postgresql.ENUM('ACT', 'DECREE', 'STATUTE', name='documenttype'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('users_files_user_id_fkey'))
    )
    op.drop_table('regulations_documents')
    op.drop_table('regulations')
    # ### end Alembic commands ###
