"""improve db constraints

Revision ID: 97e6e7761096
Revises: 50f8b07c8a77
Create Date: 2026-07-21 23:29:31.565289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97e6e7761096'
down_revision: Union[str, Sequence[str], None] = '50f8b07c8a77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regulations', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_regulations_id_user_id', ['id', 'user_id'])

    with op.batch_alter_table('regulations_documents', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'regulations', ['regulation_id', 'user_id'], ['id', 'user_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regulations_documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('regulations', schema=None) as batch_op:
        batch_op.drop_constraint('uq_regulations_id_user_id', type_='unique')

    # ### end Alembic commands ###
