"""Add tables to register files.

Revision ID: 98425aa7315d
Revises: 2839854fada0
Create Date: 2026-03-07 21:05:54.279488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98425aa7315d'
down_revision: Union[str, Sequence[str], None] = '2839854fada0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_files',
    sa.Column('file_hash', sa.String(length=32), nullable=False),
    sa.Column('presentation_name', sa.String(length=255), nullable=False),
    sa.Column('is_prepared', sa.Boolean(), nullable=False),
    sa.Column('create_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('file_hash')
    )
    op.create_table('users_files',
    sa.Column('file_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('presentation_name', sa.String(length=255), nullable=False),
    sa.Column('is_prepared', sa.Boolean(), nullable=False),
    sa.Column('create_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('file_hash', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_files')
    op.drop_table('public_files')
    # ### end Alembic commands ###
