"""Change cases articles table

Revision ID: 9cca039aa000
Revises: 8a689632de01
Create Date: 2026-05-03 14:32:17.599881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cca039aa000'
down_revision: Union[str, Sequence[str], None] = '8a689632de01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_articles', sa.Column('presentation_name', sa.String(length=255), nullable=False))
    op.drop_constraint(op.f('case_articles_case_id_fkey'), 'case_articles', type_='foreignkey')
    op.create_foreign_key(None, 'case_articles', 'cases', ['case_id'], ['id'], ondelete='CASCADE')
    op.drop_column('case_articles', 'document_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_articles', sa.Column('document_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'case_articles', type_='foreignkey')
    op.create_foreign_key(op.f('case_articles_case_id_fkey'), 'case_articles', 'cases', ['case_id'], ['id'])
    op.drop_column('case_articles', 'presentation_name')
    # ### end Alembic commands ###
