"""improve fk constraint for regulations_documents

Revision ID: 9ea79db87ac3
Revises: 292c57aec121
Create Date: 2026-07-04 23:00:28.729144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ea79db87ac3'
down_revision: Union[str, Sequence[str], None] = '292c57aec121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regulations_documents', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('regulations_documents_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('regulations_documents_regulation_id_fkey'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regulations_documents', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('regulations_documents_regulation_id_fkey'), 'regulations', ['regulation_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('regulations_documents_user_id_fkey'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
