"""change tables for s3 compatible storage

Revision ID: a45d973c4187
Revises: b1c7f3a92d44
Create Date: 2026-08-14 21:56:13.886621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a45d973c4187'
down_revision: Union[str, Sequence[str], None] = 'b1c7f3a92d44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regulations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_uploaded', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regulations', schema=None) as batch_op:
        batch_op.drop_column('is_uploaded')

    # ### end Alembic commands ###
