"""add_document_type_field

Revision ID: bf8a3b670e22
Revises: 9cca039aa000
Create Date: 2026-05-18 20:55:12.844806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf8a3b670e22'
down_revision: Union[str, Sequence[str], None] = '9cca039aa000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('public_files', sa.Column('document_type', sa.Enum('ACT', 'DECREE', 'STATUTE', name='documenttype'), nullable=True))
    op.add_column('users_files', sa.Column('document_type', sa.Enum('ACT', 'DECREE', 'STATUTE', name='documenttype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_files', 'document_type')
    op.drop_column('public_files', 'document_type')
    # ### end Alembic commands ###
