apiVersion: v1
kind: Pod
metadata:
  name: embedding-service
  labels:
    app: prawobiorca
    component: embedding-service
spec:
  containers:
    - name: embedding-service
      image: localhost/embedding-service:latest
      args:
        - --model_path=/models/mmlw-retrieval-roberta-large-v2
        - --model_name=mmlw-retrieval-roberta-large-v2
        - --task=embeddings
        - --pooling=CLS
        - --target_device=CPU
        - --rest_port=8080
      ports:
        - containerPort: 8080
          hostPort: 8081
