apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: prawobiorca
    component: nginx
spec:
  containers:
    - name: nginx
      image: docker.io/library/nginx:alpine
      ports:
        - containerPort: 8080
          hostPort: 8080
      volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
  volumes:
    - name: nginx-conf
      configMap:
        name: nginx-config
