apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: prawobiorca
    component: postgres
spec:
  containers:
    - name: postgres
      image: docker.io/pgvector/pgvector:0.8.4-pg18-trixie
      ports:
        - containerPort: 5432
          hostPort: 5432
      volumeMounts:
        - name: pg-data
          mountPath: /var/lib/postgresql
      env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_DB
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: prawobiorca-secrets
              key: POSTGRES_PASSWORD
  volumes:
    - name: pg-data
      persistentVolumeClaim:
        claimName: pg-data
