FROM python:3.13-slim-trixie

RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender1 \
    libxcb1 \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir uv

RUN useradd -m embedding_generator
WORKDIR /embedding_generator
RUN chown -R embedding_generator /embedding_generator
USER embedding_generator

COPY pyproject.toml pyproject.toml
COPY --chown=embedding_generator:embedding_generator uv.lock uv.lock

RUN uv --no-cache sync

COPY model_download.py model_download.py

RUN .venv/bin/python model_download.py

COPY src src

EXPOSE 8080

ENV PATH="/embedding_generator/.venv/bin:$PATH"

ENTRYPOINT ["granian", "--port", "8080", "--host", "0.0.0.0", "--interface", "asgi", "src.main:app"]