/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Log User */
    post: operations['log_user_api_auth_login_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/refresh': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Refresh Tokens */
    post: operations['refresh_tokens_api_auth_refresh_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Check Is User Logged */
    get: operations['check_is_user_logged_api_auth_me_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Logout User */
    post: operations['logout_user_api_auth_logout_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/regulations': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Public Regulations */
    get: operations['get_public_regulations_api_regulations_get']
    put?: never
    /** Add Public Regulation */
    post: operations['add_public_regulation_api_regulations_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/regulations/{regulationId}/documents': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Search Regulation Documents */
    get: operations['search_regulation_documents_api_regulations__regulationId__documents_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/regulations/{regulationId}/confirm-upload': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Confirm Public Regulation Upload */
    post: operations['confirm_public_regulation_upload_api_regulations__regulationId__confirm_upload_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/regulations/{regulationId}/download-url': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Public Regulation Download Url */
    get: operations['get_public_regulation_download_url_api_regulations__regulationId__download_url_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/regulations/{regulationId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Delete Public Regulation */
    delete: operations['delete_public_regulation_api_regulations__regulationId__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/regulations/{regulationId}/preparation-retry': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Retry Public Regulation Preparation */
    post: operations['retry_public_regulation_preparation_api_regulations__regulationId__preparation_retry_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/accounts/register': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Create Account */
    post: operations['create_account_api_accounts_register_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/user/cases': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Cases List */
    get: operations['get_cases_list_api_user_cases_get']
    put?: never
    /** Add Case */
    post: operations['add_case_api_user_cases_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/user/cases/{caseId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Delete User Case */
    delete: operations['delete_user_case_api_user_cases__caseId__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/user/cases/{caseId}/documents': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Case Documents */
    get: operations['get_case_documents_api_user_cases__caseId__documents_get']
    put?: never
    /** Add Case Document */
    post: operations['add_case_document_api_user_cases__caseId__documents_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/user/cases/documents/{documentId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Delete Case Document */
    delete: operations['delete_case_document_api_user_cases_documents__documentId__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/user/regulations': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get User Regulations */
    get: operations['get_user_regulations_api_user_regulations_get']
    put?: never
    /** Add User Regulation */
    post: operations['add_user_regulation_api_user_regulations_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/user/regulations/{regulationId}/confirm-upload': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Confirm User Regulation Upload */
    post: operations['confirm_user_regulation_upload_api_user_regulations__regulationId__confirm_upload_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/user/regulations/{regulationId}/download-url': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get User Regulation Download Url */
    get: operations['get_user_regulation_download_url_api_user_regulations__regulationId__download_url_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/user/regulations/{regulationId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Delete User Regulation */
    delete: operations['delete_user_regulation_api_user_regulations__regulationId__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/user/regulations/{regulationId}/documents': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Search Regulation Documents */
    get: operations['search_regulation_documents_api_user_regulations__regulationId__documents_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/user/regulations/{regulationId}/preparation-retry': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Retry User Regulation Preparation */
    post: operations['retry_user_regulation_preparation_api_user_regulations__regulationId__preparation_retry_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/health/liveness': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Health Status */
    get: operations['get_health_status_health_liveness_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/health/ready': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Check is application ready to response for requests. */
    get: operations['check_readiness_health_ready_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** Body_add_case_api_user_cases_post */
    Body_add_case_api_user_cases_post: {
      /** Casename */
      caseName: string
    }
    /** Body_log_user_api_auth_login_post */
    Body_log_user_api_auth_login_post: {
      /** Grant Type */
      grant_type?: string | null
      /** Username */
      username: string
      /**
       * Password
       * Format: password
       */
      password: string
      /**
       * Scope
       * @default
       */
      scope: string
      /** Client Id */
      client_id?: string | null
      /**
       * Client Secret
       * Format: password
       */
      client_secret?: string | null
    }
    /** CaseData */
    CaseData: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Name */
      name: string
    }
    /** CaseDocument */
    CaseDocument: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /**
       * Caseid
       * Format: uuid
       */
      caseId: string
      /** Presentationname */
      presentationName: string
      /** Content */
      content: string
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /** LoginData */
    LoginData: {
      /** Username */
      username: string
      /**
       * Password
       * Format: password
       */
      password: string
    }
    /** NewCaseDocument */
    NewCaseDocument: {
      /** Presentationname */
      presentationName: string
      /** Content */
      content: string
    }
    /** RegulationData */
    RegulationData: {
      /** Name */
      name: string
      regulationType?: components['schemas']['RegulationType'] | null
    }
    /**
     * RegulationPreparationStatus
     * @enum {string}
     */
    RegulationPreparationStatus: 'NOT_STARTED' | 'IN_PROGRESS' | 'PREPARED' | 'FAILED'
    /** RegulationRepresentation */
    RegulationRepresentation: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Presentationname */
      presentationName: string
      regulationType: components['schemas']['RegulationType'] | null
      /** @default NOT_STARTED */
      preparationStatus: components['schemas']['RegulationPreparationStatus']
    }
    /**
     * RegulationType
     * @enum {string}
     */
    RegulationType: 'ACT' | 'DECREE' | 'STATUTE'
    /** RegulationUploadTarget */
    RegulationUploadTarget: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Url */
      url: string
      /** Fields */
      fields: {
        [key: string]: string
      }
    }
    /**
     * SearchOrder
     * @enum {string}
     */
    SearchOrder: 'document' | 'score'
    /** SearchResult */
    SearchResult: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Score */
      score: number
      /** Header */
      header: string | null
      /** Text */
      text: string
      unit_type: components['schemas']['UnitType'] | null
      /** Unit Number */
      unit_number: string | null
      /** Unit Path */
      unit_path: string[] | null
      /** Elements */
      elements: components['schemas']['SearchResultElement'][] | null
      highlight: components['schemas']['SearchResultHighlight'] | null
    }
    /** SearchResultElement */
    SearchResultElement: {
      /** Text */
      text: string
      /** Subsection */
      subsection: string | null
    }
    /** SearchResultHighlight */
    SearchResultHighlight: {
      /** Start Element */
      start_element: number
      /** Start Offset */
      start_offset: number
      /** End Element */
      end_element: number
      /** End Offset */
      end_offset: number
    }
    /**
     * UnitType
     * @enum {string}
     */
    UnitType: 'ARTICLE' | 'PARAGRAPH' | 'UNNUMBERED'
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  log_user_api_auth_login_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/x-www-form-urlencoded': components['schemas']['Body_log_user_api_auth_login_post']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Incorrect logging data! */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  refresh_tokens_api_auth_refresh_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Invalid or expired refresh token! */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  check_is_user_logged_api_auth_me_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description User not logged. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  logout_user_api_auth_logout_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
  get_public_regulations_api_regulations_get: {
    parameters: {
      query?: {
        documentType?: components['schemas']['RegulationType'] | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RegulationRepresentation'][]
        }
      }
      /** @description No public files for given search criteria. */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  add_public_regulation_api_regulations_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RegulationData']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RegulationUploadTarget']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  search_regulation_documents_api_regulations__regulationId__documents_get: {
    parameters: {
      query: {
        threshold: number
        limit?: number | null
        query: string
        order_by?: components['schemas']['SearchOrder']
      }
      header?: never
      path: {
        regulationId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SearchResult'][]
        }
      }
      /** @description No search results. */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Regulation not prepared, normally should not occur. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Regulation not found. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  confirm_public_regulation_upload_api_regulations__regulationId__confirm_upload_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        regulationId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Regulation not found! */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Regulation upload already confirmed, or its content not found on storage! */
      409: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description Preparation service not working! */
      503: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  get_public_regulation_download_url_api_regulations__regulationId__download_url_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        regulationId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': string
        }
      }
      /** @description Regulation not found! */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_public_regulation_api_regulations__regulationId__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        regulationId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Regulation not found! */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  retry_public_regulation_preparation_api_regulations__regulationId__preparation_retry_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        regulationId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Regulation to prepare not found! */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Regulation already prepared, preparation in progress, or its content not uploaded! */
      409: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description Preparation service not working! */
      503: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  create_account_api_accounts_register_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginData']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description User with that login already exists. */
      409: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_cases_list_api_user_cases_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CaseData'][]
        }
      }
      /** @description No user cases. */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  add_case_api_user_cases_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/x-www-form-urlencoded': components['schemas']['Body_add_case_api_user_cases_post']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': string
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_user_case_api_user_cases__caseId__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        caseId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description No case with that id! */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_case_documents_api_user_cases__caseId__documents_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        caseId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CaseDocument'][]
        }
      }
      /** @description No documents for case. */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  add_case_document_api_user_cases__caseId__documents_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        caseId: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['NewCaseDocument']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description No case with that id! */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_case_document_api_user_cases_documents__documentId__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        documentId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_user_regulations_api_user_regulations_get: {
    parameters: {
      query?: {
        documentType?: components['schemas']['RegulationType'] | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RegulationRepresentation'][]
        }
      }
      /** @description Not found user files with that criteria. */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  add_user_regulation_api_user_regulations_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RegulationData']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RegulationUploadTarget']
        }
      }
      /** @description Can't add empty regulation. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description User not found! */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  confirm_user_regulation_upload_api_user_regulations__regulationId__confirm_upload_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        regulationId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Regulation not found! */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Regulation upload already confirmed, or its content not found on storage! */
      409: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description Preparation service not working! */
      503: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  get_user_regulation_download_url_api_user_regulations__regulationId__download_url_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        regulationId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': string
        }
      }
      /** @description Regulation not found! */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_user_regulation_api_user_regulations__regulationId__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        regulationId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Regulation not found! */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  search_regulation_documents_api_user_regulations__regulationId__documents_get: {
    parameters: {
      query: {
        threshold: number
        limit?: number | null
        query: string
        order_by?: components['schemas']['SearchOrder']
      }
      header?: never
      path: {
        regulationId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SearchResult'][]
        }
      }
      /** @description No search results. */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Regulation not prepared, by user, can't search. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Regulation not found. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  retry_user_regulation_preparation_api_user_regulations__regulationId__preparation_retry_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        regulationId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Regulation to prepare not found! */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Regulation already prepared, preparation in progress, or its content not uploaded! */
      409: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description Preparation service not working! */
      503: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  get_health_status_health_liveness_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': 'OK'
        }
      }
      /** @description Service unavailable. */
      503: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  check_readiness_health_ready_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': true
        }
      }
      /** @description Service unavailable. */
      503: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
}
