AUTHORIZATION_TOKEN_LENGTH = 32

SECURITY_MIN_RESPONSE_TIME = 2.0

AUTHORIZATION_COOKIE_NAME = "authorization_token"

MIN_FILENAME_LENGTH = 1

MAX_FILENAME_LENGTH = 255

VECTOR_LENGTH = 768

REGULATION_PREPARATION_TASK_NAME = "prepare_regulation"

MAX_REGULATION_PREPARATION_ATTEMPTS = 3
