AUTHORIZATION_TOKEN_LENGTH = 32

SECURITY_MIN_RESPONSE_TIME = 2.0

ACCESS_COOKIE_NAME = "access_token"

REFRESH_COOKIE_NAME = "refresh_token"

AUTH_COOKIE_PATH = "/api"

REFRESH_COOKIE_PATH = "/api/auth"

MIN_FILENAME_LENGTH = 1

MAX_FILENAME_LENGTH = 255

VECTOR_LENGTH = 768

REGULATION_PREPARATION_TASK_NAME = "prepare_regulation"

MAX_REGULATION_PREPARATION_ATTEMPTS = 3
