BEARER_TOKEN_LENGTH = 32

EMAIL_VERIFICATION_TOKEN_LENGTH = 32

SECURITY_MIN_RESPONSE_TIME = 2.0

DEFAULT_URL_EXPIRY = 900

ACCESS_TOKEN_EXPIRATION_SECONDS = 3600

REFRESH_TOKEN_EXPIRATION_SECONDS = 60 * 60 * 24 * 30
