apiVersion: v1
kind: ConfigMap
metadata:
  name: prawobiorca-backend-config
data:
  APP_LOGGING_LEVEL: "INFO"
  APP_JWT_ALGORITHM: "HS256"
  APP_ACCESS_TOKEN_EXPIRATION_SECONDS: "900"
  APP_REFRESH_TOKEN_EXPIRATION_SECONDS: "1209600"
  APP_COOKIE_SECURE: "true"
  APP_COOKIE_SAMESITE: "lax"
  APP_HTTP_CLIENT: "HTTPX"
  APP_DOCUMENT_DESIRED_TOKENS_LENGTH: "300"

  RELATIONAL_DB_DRIVER: "postgresql+asyncpg"
  RELATIONAL_DB_USER: "postgres"
  RELATIONAL_DB_HOST: "postgres"
  RELATIONAL_DB_PORT: "5432"
  RELATIONAL_DB_NAME: "postgres"
  RELATIONAL_DB_POOL_SIZE: "50"
  RELATIONAL_DB_MAX_OVERFLOW: "20"
  RELATIONAL_DB_POOL_TIMEOUT: "30"
  RELATIONAL_DB_POOL_RECYCLE: "5"

  HTTPX_TIMEOUT: "30"
  HTTPX_MAX_CONNECTIONS: "20"
  HTTPX_MAX_KEEP_ALIVE_CONNECTIONS: "5"

  EMBEDDING_SERVICE_URL: "http://embedding-service:8080"
  EXTRACTION_SERVICE_URL: "http://extraction-service:8080"
  TOKENIZER_MAX_TOKENS: "2048"
  TOKENIZER_MAX_TITLE_TOKENS_OVERHEAD: "16"

  BROKER_URL: "redis://redis:6379"

  OBJECT_STORAGE_ENDPOINT_URL: "https://storage.googleapis.com"
  OBJECT_STORAGE_REGION: "europe-central2"
  OBJECT_STORAGE_BUCKET: "prawobiorca-regulations"
  OBJECT_STORAGE_SIGNED_URL_EXPIRATION_SECONDS: "3600"
  OBJECT_STORAGE_MAX_FILE_SIZE_BYTES: "10485760"
