apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: prawobiorca-backend-cert
spec:
  domains:
    - www.prawobiorca.pl

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prawobiorca-backend
  annotations:
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/managed-certificates: prawobiorca-backend-cert
spec:
  rules:
    - host: www.prawobiorca.pl
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: prawobiorca-backend
                port:
                  number: 8000
          - path: /docs
            pathType: Prefix
            backend:
              service:
                name: prawobiorca-backend
                port:
                  number: 8000
          - path: /openapi.json
            pathType: Exact
            backend:
              service:
                name: prawobiorca-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prawobiorca-frontend
                port:
                  number: 8000
