apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: prawobiorca-secrets
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/prawobiorca/secrets/postgres-password/versions/latest"
        path: "postgres-password"
      - resourceName: "projects/prawobiorca/secrets/object-storage-access-key/versions/latest"
        path: "object-storage-access-key"
      - resourceName: "projects/prawobiorca/secrets/object-storage-secret-key/versions/latest"
        path: "object-storage-secret-key"
  secretObjects:
    - secretName: prawobiorca-secrets
      type: Opaque
      data:
        - objectName: postgres-password
          key: POSTGRES_PASSWORD
        - objectName: object-storage-access-key
          key: OBJECT_STORAGE_ACCESS_KEY
        - objectName: object-storage-secret-key
          key: OBJECT_STORAGE_SECRET_KEY
