apiVersion: v1
kind: Pod
metadata:
  name: prawobiorca-worker
  labels:
    app: prawobiorca
    component: prawobiorca-worker
spec:
  containers:
    - name: prawobiorca-worker
      image: localhost/prawobiorca-backend:latest
      command: ["taskiq", "worker", "app.framework.workers.regulations:broker"]
      envFrom:
        - configMapRef:
            name: prawobiorca-backend-config
      env:
        - name: APP_JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: prawobiorca-secrets
              key: JWT_SECRET_KEY
        - name: RELATIONAL_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: prawobiorca-secrets
              key: POSTGRES_PASSWORD
