apiVersion: v1
kind: Pod
metadata:
  name: prawobiorca-frontend
  labels:
    app: prawobiorca
    component: prawobiorca-frontend
spec:
  containers:
    - name: prawobiorca-frontend
      image: localhost/prawobiorca-frontend:latest
      ports:
        - containerPort: 8000
