apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: prawobiorca
    component: redis
spec:
  containers:
    - name: redis
      image: docker.io/library/redis:8-alpine
      ports:
        - containerPort: 6379
          hostPort: 6379
