apiVersion: v1
kind: Pod
metadata:
  name: rustfs
  labels:
    app: prawobiorca
    component: rustfs
spec:
  containers:
    - name: rustfs
      image: docker.io/rustfs/rustfs:latest
      env:
        - name: RUSTFS_CORS_ALLOWED_ORIGINS
          value: "*"
      ports:
        - containerPort: 9000
          hostPort: 9000
        - containerPort: 9001
      volumeMounts:
        - name: rustfs-data
          mountPath: /data
  volumes:
    - name: rustfs-data
      persistentVolumeClaim:
        claimName: rustfs-data
