apiVersion: v1
kind: ConfigMap
metadata:
  name: prawobiorca-backend-config
data:
  APP_LOGGING_LEVEL: "INFO"
  APP_COOKIE_SECURE: "true"

  RELATIONAL_DB_USER: "postgres"
  RELATIONAL_DB_HOST: "postgres"
  RELATIONAL_DB_PORT: "5432"
  RELATIONAL_DB_NAME: "postgres"

  EMBEDDING_SERVICE_URL: "http://embedding-service:8080"
  EXTRACTION_SERVICE_URL: "http://extraction-service:8080"

  BROKER_URL: "redis://redis:6379"

  OBJECT_STORAGE_ENDPOINT_URL: "https://storage.googleapis.com"
  OBJECT_STORAGE_REGION: "europe-central2"
  OBJECT_STORAGE_BUCKET: "prawobiorca-regulations"
