apiVersion: apps/v1
kind: Deployment
metadata:
  name: embedding-service
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prawobiorca
      component: embedding-service
  template:
    metadata:
      labels:
        app: prawobiorca
        component: embedding-service
    spec:
      containers:
        - name: embedding-service
          image: europe-central2-docker.pkg.dev/prawobiorca/prawobiorca-repo/embedding-service:latest
          args:
            - --model_path=/models/mmlw-retrieval-roberta-large-v2
            - --model_name=mmlw-retrieval-roberta-large-v2
            - --task=embeddings
            - --pooling=CLS
            - --target_device=CPU
            - --rest_port=8080
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "500m"
              memory: "1.5Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
          startupProbe:
            httpGet:
              path: /v2/health/live
              port: 8080
            periodSeconds: 10
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /v2/health/ready
              port: 8080
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /v2/health/live
              port: 8080
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: embedding-service
spec:
  selector:
    app: prawobiorca
    component: embedding-service
  ports:
    - port: 8080
      targetPort: 8080
