apiVersion: apps/v1
kind: Deployment
metadata:
  name: extraction-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prawobiorca
      component: extraction-service
  template:
    metadata:
      labels:
        app: prawobiorca
        component: extraction-service
    spec:
      containers:
        - name: extraction-service
          image: europe-central2-docker.pkg.dev/prawobiorca/prawobiorca-repo/extraction-service:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "500m"
              memory: "1.5Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 10
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: extraction-service
spec:
  selector:
    app: prawobiorca
    component: extraction-service
  ports:
    - port: 8080
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: extraction-service-proxy
spec:
  type: ExternalName
  externalName: keda-add-ons-http-interceptor-proxy.keda.svc.cluster.local

---
apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: extraction-service
spec:
  hosts:
    - extraction-service-proxy
  scaleTargetRef:
    name: extraction-service
    kind: Deployment
    apiVersion: apps/v1
    service: extraction-service
    port: 8080
  replicas:
    min: 0
    max: 1
  timeouts:
    conditionWait: 5m
    responseHeader: 25m
