apiVersion: batch/v1
kind: Job
metadata:
  name: prawobiorca-migrations
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: prawobiorca
        component: prawobiorca-migrations
    spec:
      serviceAccountName: prawobiorca-runner
      restartPolicy: Never
      containers:
        - name: prawobiorca-migrations
          image: europe-central2-docker.pkg.dev/prawobiorca/prawobiorca-repo/prawobiorca-backend:latest
          command: ["alembic", "upgrade", "head"]
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: secrets-store
              mountPath: "/mnt/secrets-store"
              readOnly: true
          envFrom:
            - configMapRef:
                name: prawobiorca-backend-config
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store-gke.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: prawobiorca-secrets
