apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: prawobiorca-secrets
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/prawobiorca/secrets/postgres-password/versions/latest"
        path: "RELATIONAL_DB_PASSWORD"
      - resourceName: "projects/prawobiorca/secrets/jwt-secret-key/versions/latest"
        path: "APP_JWT_SECRET_KEY"
      - resourceName: "projects/prawobiorca/secrets/object-storage-access-key/versions/latest"
        path: "OBJECT_STORAGE_ACCESS_KEY"
      - resourceName: "projects/prawobiorca/secrets/object-storage-secret-key/versions/latest"
        path: "OBJECT_STORAGE_SECRET_KEY"
