[project]
name = "text-transformator"
version = "0.5.2"
description = "Service to make various ai operations on texts: splitting, embeddding."
requires-python = "==3.14.*"
dependencies = [
    "docling==2.110.*",
    "fastapi==0.139.*",
    "granian==2.7.*",
    "onnxruntime==1.27.*",
    "python-multipart==0.0.32",
    "transformers==5.08.*",
]
