[project]
name = "text-transformator"
version = "0.5.1"
description = "Service to make various ai operations on texts: splitting, embeddding."
requires-python = "==3.14.*"
dependencies = [
    "docling==2.93.*",
    "fastapi==0.136.*",
    "granian==2.7.*",
    "onnxruntime==1.26.*",
    "python-multipart==0.0.28",
    "transformers==5.8.*",
]
