FROM python:3.14-slim-trixie

RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender1 \
    libxcb1 \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache uv==0.11.*

RUN useradd -m extraction_service

WORKDIR /extraction-service
RUN chown extraction_service /extraction-service

USER extraction_service

COPY pyproject.toml pyproject.toml
COPY uv.lock uv.lock

RUN uv sync --compile-bytecode --no-cache

COPY src src

EXPOSE 8080

ENV PATH="/extraction-service/.venv/bin:$PATH"

ENTRYPOINT ["granian", "--port", "8080", "--host", "0.0.0.0", "--interface", "asgi", "src.main:app"]
