[project]
name = "extraction-service"
version = "0.1.0"
description = "Service to parse and extract text from documents."
license = "MIT"
requires-python = "==3.14.*"
dependencies = [
    "docling==2.110.*",
    "fastapi==0.139.*",
    "granian==2.7.*",
    "python-multipart==0.0.32",
    "torch==2.13.*",
    "torchvision==0.28.*",
]

[dependency-groups]
test = [
    "httpx2==2.12.*",
    "pytest==9.1.*",
    "testcontainers==4.15.*",
]

[tool.uv.sources]
torch = { index = "pytorch-cpu" }
torchvision = { index = "pytorch-cpu" }

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
